---
title: "plot WRF: Cross sections"
author: "Sergio Ibarra-Espinosa"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{plot WRF: Cross sections}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Based on this [NCL](https://www.ncl.ucar.edu/Applications/wrf.shtml) 

```{r}
library(eixport)
library(raster)
library(stars)
library(cptcity)
library(sf)
library(vein)
```


Adding coastlines and cropping for our study area
```{r}
cl <- st_read("/media/sergio/ext4/coasts_shapefile/gshhg-shp-2.3.7/GSHHS_shp/f/GSHHS_f_L1.shp")
```


Reading Temperature and crop coast lines for our study area
```{r}
t2 <- wrf_get("/media/sergio/ext4/wrfoETA_COM_VEIN/wrfout_d03_2014-10-03_00:00:00", 
              "T2", as_raster = T)
t2 <- t2 -273.15
cl <- st_cast(st_crop(cl, st_as_stars(t2)), "LINESTRING") # 
```

Find colour palette for temperature
```{r}
find_cpt("temperature")
```


Let us create a line between c(-46.5,-23.85) and c(-46.35, -23.95)

```{r}
m <- cbind(c(-46.5, -46.35),  # xini xend
           c(-23.85, -23.95)) # yini yend
cross = st_linestring(m)
(cross <- st_sfc(cross, crs = 4326))
plot(t2$T2_2014.10.06_14.00.00, 
     main = "Temperature using plot", 
     col = cpt("arendal_temperature"))
plot(cross, add = T)
plot(cl$geometry, add = T)
```

Now, define several lines
```{r}
m2 <- cbind(c(-46.05, -46.36),  # xini xend
            c(-23.85, -23.95))   # yini yend
```

Define a helper function
```{r}
points_extract <- function(m, sta) {
  cross = st_linestring(m)
  cross <- st_sfc(cross, crs = 4326)
  t2s <- st_as_sf(sta)
  lt <- st_intersection(t2s, cross) 
  geo <- st_geometry(lt)
  lt <- st_set_geometry(lt, NULL)
  na <- names(lt)
  lt$id <- 1:nrow(lt)
  dx <- vein::wide_to_long(df = lt, 
                           column_with_data = na, 
                           column_fixed = "id")
  stf <- st_sf(dx, geometry = geo)
  lt <- st_centroid(stf)
  lt <- cbind(lt, st_coordinates(lt))
  
  return(lt)
}
```


```{r}
library(ggplot2)
sta = st_as_stars(t2)
names(sta) <- "temperature"
df <- points_extract(m, sta = sta)
```
Let us check the data
```{r}
head(df)
```

Add time variable, select and plot
```{r}
df$time <- as.POSIXct(df$V3, format = "T2_%Y.%m.%d_%H.%M.%S")
df$hour <- strftime(df$time, "%H")
ggplot(df[df$hour %in% "15", ], 
       aes(x = X, y = V1, colour = as.factor(time))) +
  labs(y =expression(paste("Temperature [",degree,"C]")),
       x = expression(paste("Longitude [",degree,"]")))+
  geom_line() +
  theme_bw()+
  theme(legend.title = element_blank())
```
