name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          r: release
        - os: ubuntu-latest
          r: devel
        - os: windows-latest
          r: release
        - os: macos-latest
          r: release
      
    env:
      RSPM: https://packagemanager.posit.co/cran/latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
          cache: true

      - name: Check
        run: rcmdcheck::rcmdcheck(args = c("--no-manual"), error_on = "warning")
        shell: Rscript {0}
